name: CocoaPods Lint
on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  lint:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-14
            xcode: 15.4
          - os: macos-15
            xcode: 16.4
          - os: macos-26
            xcode: 26.1
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup CocoaPods
        uses: maxim-lobanov/setup-cocoapods@v1
        with:
          version: latest
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ matrix.xcode }}
      - name: Library Lint
        id: lib-lint
        run: |
          validation_dir=$(mktemp -d)
          echo "validation_dir=${validation_dir}" >> $GITHUB_OUTPUT
          pod lib lint \
            --validation-dir="${validation_dir}" \
            --no-clean \
            --allow-warnings \
            --verbose \
            --sources=https://github.com/livekit/podspecs.git/,https://cdn.cocoapods.org/
      - name: Upload Validation Directory (Failure Only)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          path: ${{ steps.lib-lint.outputs.validation_dir }}
          name: validation-xcode${{ matrix.xcode }}
